# Only build tags
if: tag IS present
language: objective-c
osx_image: xcode9.4
xcode_project: "OpenVPN Adapter.xcodeproj"
# xcode_workspace: <WORKSPACE_PLACEHOLDER>
# xcode_scheme: "scheme"
# xcode_sdk: iphonesimulator9.3
env:
  global:
    - FRAMEWORK_NAME=OpenVPNAdapter
# before_install:
before_script:
  - bash update_carthage.sh 0.30.1
  - git config --local user.name "MeGaPk"
  - git config --local user.email "megapk@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  # - carthage bootstrap
script:
  - carthage update
  - zip -r "open_vpn_adapter_ios.zip" Carthage/Build/iOS/OpenVPNAdapter.framework/
  - zip -r "open_vpn_adapter_osx.zip" Carthage/Build/Mac/OpenVPNAdapter.framework/
deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_KEY
  file:
      - open_vpn_adapter_ios.zip
      - open_vpn_adapter_osx.zip
  skip_cleanup: true
  on:
    tags: true
    repo: MeGaPk/OpenVPNAdapter
