language: objective-c
osx_image: xcode9
xcode_project: "OpenVPN Adapter.xcodeproj"
# xcode_workspace: <WORKSPACE_PLACEHOLDER>
xcode_scheme: "scheme"
# xcode_sdk: iphonesimulator9.3
env:
  global:
    - FRAMEWORK_NAME=OpenVPNAdapter
before_install:
  - bash update_carthage.sh 0.30.1
  # - brew update
  # - brew outdated carthage || brew upgrade carthage
# before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  # - carthage bootstrap
# before_deploy:
  # - carthage buildtravis compile  --no-skip-current
  # - carthage archive $FRAMEWORK_NAME
