# Only build tags
if: tag IS present
language: objective-c
osx_image: xcode9.4
xcode_project: "OpenVPN Adapter.xcodeproj"
env:
  global:
    - FRAMEWORK_NAME=OpenVPNAdapter
# before_install:
before_script:
  - bash update_carthage.sh 0.30.1
  - git config --local user.name "MeGaPk"
  - git config --local user.email "megapk@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  # - carthage bootstrap
script:
  - carthage update --no-use-binaries
  - mkdir -p ios osx
  - mv Carthage/Build/iOS/OpenVPNAdapter.framework/ ios/
  - mv Carthage/Build/Mac/OpenVPNAdapter.framework/ osx/
  - zip --symlinks -r "OpenVPNAdapter.framework.zip" ios/ osx/ LICENSE
deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_KEY
  file: OpenVPNAdapter.framework.zip
  skip_cleanup: true
  on:
    tags: true
    repo: MeGaPk/OpenVPNAdapter
# after_deploy:
# TODO: here need put some code for release podspec file to cocoapods official repository
